project:
  type: website

website:
  title: "Schoter - VIX Talent Database"
  navbar:
    background: primary
    left:
      - text: Dashboard
        menu: 
          - href: cw.qmd
            text: Schoter - Copywriter
          - href: mobile.qmd
            text: Schoter - Mobile Aps Developer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

